# Generated by Django 4.2.2 on 2023-07-20 10:29

import clipboardShare.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecretClipboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('content', models.TextField()),
                ('posted_by', models.CharField(blank=True, default='anonymousUser', max_length=100)),
                ('expire_at', models.DateTimeField(blank=True, default=clipboardShare.models.expire_time_maker)),
            ],
        ),
    ]
