# Generated by Django 4.2.2 on 2023-07-20 10:29

from django.db import migrations, models
import lightfileShare.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecretFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('content', models.FileField(upload_to='lightfile/shared/')),
                ('posted_by', models.CharField(blank=True, default='anonymousUser', max_length=100)),
                ('expire_at', models.DateTimeField(blank=True, default=lightfileShare.models.expire_time_maker)),
            ],
        ),
    ]
